.deploy/naiserator.yaml
Trenger å legge til tokenx for å få lov til å veksle token i frontend-server
=> enable tokenx

src/main/java/no/nav/familie/inntektsmelding/integrasjoner/organisasjon/EregKlient.java, src/main/java/no/nav/familie/inntektsmelding/integrasjoner/organisasjon/OrganisasjonsNummerValidator.java, src/main/java/no/nav/familie/inntektsmelding/integrasjoner/person/AktørId.java, src/main/java/no/nav/familie/inntektsmelding/integrasjoner/person/PdlKlient.java
Hei, 
Tenkte å skjule disse klient implementasjonene - blir noe enklere med koding senere om kun tjenestene eller interfacene og Dtoene er public.
=> Skjuler klient implenentasjoner bak tjenesten/interfacet.

src/main/java/no/nav/familie/inntektsmelding/rest/imdialog/InntektsmeldingDialogRest.java, src/main/java/no/nav/familie/inntektsmelding/server/ApiConfig.java
Jeg forslår å flytte `imdialog/rest/` -> `rest/imdialog/` slik at vi an legge til forespørsel i `rest/forespørsel`
=> flytte rest pakke for imdialog

src/main/java/no/nav/familie/inntektsmelding/database/tjenester/InnkommendeForespørselTjeneste.java, src/main/java/no/nav/familie/inntektsmelding/forepørsel/rest/ForespørselRestTjeneste.java, src/main/java/no/nav/familie/inntektsmelding/imdialog/InntektsmeldingDialogRest.java, src/main/java/no/nav/familie/inntektsmelding/integrasjoner/person/PersonInfo.java, src/main/java/no/nav/familie/inntektsmelding/integrasjoner/person/PersonTjeneste.java, src/main/java/no/nav/familie/inntektsmelding/typer/YtelseTypeMapper.java, src/test/java/no/nav/familie/inntektsmelding/database/tjenester/InnkommendeForespørselTjenesteTest.java, src/test/java/no/nav/familie/inntektsmelding/forepørsel/rest/ForespørselRestTjenesteTest.java
=> feat: legge person i sakstittel

src/main/java/no/nav/familie/inntektsmelding/forespørsel/modell/ForespørselEntitet.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/modell/ForespørselRepository.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/rest/ForespørselRest.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/rest/OpprettForespørselRequest.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselTjeneste.java, src/main/java/no/nav/familie/inntektsmelding/forvaltning/FagerTestRestTjeneste.java, src/main/java/no/nav/familie/inntektsmelding/typer/OrganisasjonsnummerValidator.java, src/main/java/no/nav/familie/inntektsmelding/typer/SaksnummerDto.java, src/main/java/no/nav/familie/inntektsmelding/typer/YtelseTypeMapper.java, src/test/java/no/nav/familie/inntektsmelding/forespørsel/rest/ForespørselRestTest.java, src/test/java/no/nav/familie/inntektsmelding/integrasjoner/arbeidsgivernotifikasjon/MerkelappTest.java, src/test/java/no/nav/familie/inntektsmelding/typer/SaksnummerDtoTest.java
Jeg endret noe på endepunkter i ForespørselRest til å være noe mer CRUD compliant.  
@johannbm det må nok tilpasses i GUI senere også.
=> SaksnummerDto record som følger standarden.

src/main/java/no/nav/familie/inntektsmelding/forespørsel/rest/ForespørselRest.java, src/main/java/no/nav/familie/inntektsmelding/forvaltning/FagerTestRestTjeneste.java, src/main/java/no/nav/familie/inntektsmelding/imdialog/rest/InntektsmeldingDialogRest.java, src/main/java/no/nav/familie/inntektsmelding/integrasjoner/altinn/AltinnAutoriseringKlient.java
I tillegg kastes exception på Test endepunkter i prod
=> Legger på @deprecated annoteringer på endepunkter som skal fjernes.

.deploy/fp/dev-gcp-teamforeldrepenger.json, .deploy/fp/naiserator.yaml, .deploy/fp/prod-gcp-teamforeldrepenger.json, .deploy/k9/naiserator.yaml
@espenjv jeg lå inn altinn-rettigheter-proxy i k9 konfig.
=> FP: Gir tilgang til drift. Fjerne konfig som ikke er i bruk.

src/main/java/no/nav/familie/inntektsmelding/imdialog/rest/InntektsmeldingDialogRest.java
Denne PRen fjerner noen endepunkt som ikke lenger brukes av frontenden.
=> Fjern endepunkter som ikke lenger brukes av frontend

src/main/resources/db/postgres/defaultDS/V1.0_006__endre_naturalytelse.sql
Det var like greit å opprette ny tabell, og med tanke på å samle alt til ett script før prodsetting tenkte jeg det var like greit.
=> POFIM-36 Oppretter ny tabell for naturalytelse

src/main/java/no/nav/familie/inntektsmelding/forespørsel/modell/ForespørselEntitet.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/modell/ForespørselRepository.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/rest/ForespørselRest.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/rest/LukkForespørselRequest.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/rest/OppdaterForespørslerISakRequest.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/rest/OppdaterForespørslerRequest.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/rest/OpprettForespørselRequest.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjeneste.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjenesteImpl.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselTjeneste.java, src/main/java/no/nav/familie/inntektsmelding/forvaltning/FagerTestRestTjeneste.java, src/main/java/no/nav/familie/inntektsmelding/integrasjoner/arbeidsgivernotifikasjon/ArbeidsgiverNotifikasjon.java, src/main/java/no/nav/familie/inntektsmelding/integrasjoner/arbeidsgivernotifikasjon/ArbeidsgiverNotifikasjonKlient.java, src/main/java/no/nav/familie/inntektsmelding/integrasjoner/arbeidsgivernotifikasjon/ArbeidsgiverNotifikasjonTjeneste.java, src/main/java/no/nav/familie/inntektsmelding/koder/ForespørselStatus.java, src/test/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjenesteImplTest.java, src/test/java/no/nav/familie/inntektsmelding/integrasjoner/arbeidsgivernotifikasjon/ArbeidsgiverNotifikasjonKlientTest.java, src/test/java/no/nav/familie/inntektsmelding/integrasjoner/arbeidsgivernotifikasjon/ArbeidsgiverNotifikasjonTjenesteTest.java
Støtte for å sende en uttømmende liste med forespørsler fra k9-sak. Vi vil opprette de som ikke finnes fra før og slette (markere oppgaven som utgått) de som ikke trengs lenger.
=> Oppdater alle forespørsler

src/main/java/no/nav/familie/inntektsmelding/forvaltning/FpDokgenRestTjeneste.java, src/main/java/no/nav/familie/inntektsmelding/imdialog/task/InntektsmeldingXMLMapper.java, src/main/java/no/nav/familie/inntektsmelding/integrasjoner/dokgen/Endringsarsak.java, src/main/java/no/nav/familie/inntektsmelding/integrasjoner/dokgen/InntektsmeldingPdfData.java, src/main/java/no/nav/familie/inntektsmelding/integrasjoner/dokgen/InntektsmeldingPdfDataMapper.java, src/main/java/no/nav/familie/inntektsmelding/integrasjoner/dokgen/NaturalYtelse.java, src/main/java/no/nav/familie/inntektsmelding/koder/Endringsårsak.java, src/main/java/no/nav/familie/inntektsmelding/utils/mapper/NaturalYtelseMapper.java, src/test/java/no/nav/familie/inntektsmelding/integrasjoner/dokgen/InntektsmeldingPdfDataMapperTest.java, src/test/java/no/nav/familie/inntektsmelding/utils/mapper/NaturalYtelseMapperTest.java
Det er også implementert generelle designendringer
=> POFIM-50 Endringsårsak i pdf

src/main/java/no/nav/familie/inntektsmelding/forespørsel/rest/ForespørselRest.java, src/main/java/no/nav/familie/inntektsmelding/forvaltning/FpDokgenRestTjeneste.java, src/main/java/no/nav/familie/inntektsmelding/forvaltning/ProsessTaskRestTjeneste.java, src/main/java/no/nav/familie/inntektsmelding/imdialog/rest/InntektsmeldingDialogRest.java, src/main/java/no/nav/familie/inntektsmelding/overstyring/InntektsmeldingFpsakRest.java, src/main/java/no/nav/familie/inntektsmelding/server/auth/api/Tilgangskontrollert.java, src/test/java/no/nav/familie/inntektsmelding/server/RestApiAutentiseringAnnoteringTest.java, src/test/java/no/nav/familie/inntektsmelding/server/RestApiAutoriseringAnnoteringTest.java
Annoteringen gjør ikke noe mer en å feile en test som validerer om alle REST endepunkter er annotert med den.
Feilmeldingen forklarer hva skal gjøres og hvordan.
=> Innfører en Tilgangskontroll annotering for å skape en bedre forståelse over logikk

src/main/java/no/nav/familie/inntektsmelding/forespørsel/modell/ForespørselEntitet.java
Det ble oppdaget at status for Forespørsel ikke oppdaterer seg og faller ut av sync med FAGER. 
Gjør status-kolonnen i ForespørselEntitet updatable.
=> Gjør status kolonnen i ForespørselEntitet updateable

src/main/java/no/nav/familie/inntektsmelding/integrasjoner/dokgen/InntektsmeldingPdfData.java, src/main/java/no/nav/familie/inntektsmelding/integrasjoner/dokgen/InntektsmeldingPdfDataMapper.java, src/test/java/no/nav/familie/inntektsmelding/integrasjoner/dokgen/InntektsmeldingPdfDataMapperTest.java
Fjerner fornavnSøker og fikser format på dato som benyttes for refusjonsnendringer og naturalytelser
=> POFIM-50 inntektsmelding pdf

src/main/java/no/nav/familie/inntektsmelding/forespørsel/rest/ForespørselRest.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjeneste.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjenesteImpl.java
Reverts navikt/ft-inntektsmelding#152
=> Revert "Nytt endepunkt for lukking av alle forespørseler tilknyttet en fagsak"

src/main/java/no/nav/familie/inntektsmelding/integrasjoner/dokgen/FpDokgenKlient.java, src/main/java/no/nav/familie/inntektsmelding/metrikker/MetrikkerTjeneste.java
Det blir noe enklere å plukke opp metrikker som tilhører FP etterpå.
Fikser en del ting sonar klager på.
Fikser i grafana etterpå.
=> Feat: forenkler håndtering av endringsårsaker per ytelse og app

src/main/java/no/nav/familie/inntektsmelding/metrikker/MetrikkerTjeneste.java
De blir synlig i prometheus som en - koblet sortert liste
=> Fix: Flere endringsårsaker logges i prometheus.

src/main/java/no/nav/familie/inntektsmelding/integrasjoner/arbeidsgivernotifikasjon/ArbeidsgiverNotifikasjonTjeneste.java, src/main/java/no/nav/familie/inntektsmelding/integrasjoner/joark/JoarkTjeneste.java
Lar den bare ligge her til den er avklart.
=> POFIM-127: Utsetter varsel med 15 minutter.

src/main/java/no/nav/familie/inntektsmelding/forespørsel/modell/ForespørselRepository.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/rest/ForespørselRest.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjeneste.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjenesteImpl.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselTjeneste.java, src/test/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjenesteImplTest.java
This reverts commit 2fbe8fa0177574fb53da0b7d8c0b29af367e50e7.
=> Revert "POFIM-81 Endring for endepunkt /sett-til-utgatt (#261)"

.deploy/fp/naiserator.yaml
=> chore: logging i grafana i tillegg til kibana

src/main/java/no/nav/familie/inntektsmelding/forespørsel/rest/ForespørselRest.java, src/main/java/no/nav/familie/inntektsmelding/typer/dto/SaksnummerDto.java, src/test/java/no/nav/familie/inntektsmelding/forespørsel/rest/ForespørselRestTest.java
https://jira.adeo.no/browse/POFIM-145
=> Resttjeneste for å hente forespørsler på sak

.deploy/fp/naiserator.yaml
Legger til navident i claims også for FP.
=> Legger til navident i claims for FP

src/main/java/no/nav/familie/inntektsmelding/forespørsel/rest/OppdaterForespørselDto.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/rest/OppdaterForespørslerRequest.java, src/test/java/no/nav/familie/inntektsmelding/forespørsel/rest/ForespørselRestTest.java, src/test/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjenesteImplTest.java
Se https://github.com/navikt/k9-sak/pull/11365
=> fjerner deprekerte felter i oppdater-forespørsler request

src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjenesteImpl.java, src/main/java/no/nav/familie/inntektsmelding/typer/dto/ForespørselAksjon.java, src/test/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjenesteImplTest.java
https://github.com/navikt/k9-sak/pull/11390
=> Egen aksjon for gjenopprett

src/main/java/no/nav/familie/inntektsmelding/server/app/api/ApiConfig.java
Man må huske på å inkludere alle REST-endepunkt i API-configen, for at det skal bli synlig.
=> Inkluder det nye rest-endepunktet i API-configen

src/main/java/no/nav/familie/inntektsmelding/integrasjoner/aareg/AaregRestKlient.java
siden det er det som brukes av andre tjenester
=> Bruk Azure AD token flow istedenfor adaptive

src/main/java/no/nav/familie/inntektsmelding/imdialog/rest/ArbeidsgiverinitiertDialogRest.java, src/main/java/no/nav/familie/inntektsmelding/imdialog/rest/OpplysningerRequestDto.java, src/main/java/no/nav/familie/inntektsmelding/imdialog/rest/SlåOppArbeidstakerResponseDto.java, src/main/java/no/nav/familie/inntektsmelding/imdialog/tjenester/InntektsmeldingTjeneste.java, src/main/java/no/nav/familie/inntektsmelding/integrasjoner/aareg/AaregRestKlient.java, src/main/java/no/nav/familie/inntektsmelding/integrasjoner/aareg/dto/ArbeidsforholdDto.java, src/main/java/no/nav/familie/inntektsmelding/refusjonomsorgsdagerarbeidsgiver/rest/RefusjonOmsorgsdagerArbeidsgiverRest.java, src/main/java/no/nav/familie/inntektsmelding/refusjonomsorgsdagerarbeidsgiver/tjenester/ArbeidsforholdTjeneste.java, src/main/java/no/nav/familie/inntektsmelding/refusjonomsorgsdagerarbeidsgiver/tjenester/ArbeidstakerTjeneste.java, src/test/java/no/nav/familie/inntektsmelding/imdialog/tjenester/InntektsmeldingTjenesteTest.java, src/test/java/no/nav/familie/inntektsmelding/integrasjoner/aareg/AaregRestKlientTest.java, src/test/java/no/nav/familie/inntektsmelding/refusjonomsorgsdagerarbeidsgiver/rest/RefusjonOmsorgsdagerArbeidsgiverRestTest.java, src/test/java/no/nav/familie/inntektsmelding/refusjonomsorgsdagerarbeidsgiver/tjenester/ArbeidsforholdTjenesteTest.java, src/test/java/no/nav/familie/inntektsmelding/refusjonomsorgsdagerarbeidsgiver/tjenester/ArbeidstakerTjenesteTest.java
Legger til første fraværsdag i requestDTO og legger til json annotasjoner i håp om at aareg integrasjon funker.
=> Pofim 169 hent arbeidsforhold for fnr

pom.xml, src/main/java/no/nav/familie/inntektsmelding/server/app/forvaltning/ForvaltningApiConfig.java, src/test/java/no/nav/familie/inntektsmelding/server/RestApiTester.java
Hensikt: muliggjøre autentisering mot prosesstasktjenesten i swagger
=> ProsessTaskRestTjeneste fra k9-prosesstask

pom.xml, src/main/java/no/nav/familie/inntektsmelding/server/app/forvaltning/ForvaltningApiConfig.java, src/test/java/no/nav/familie/inntektsmelding/server/RestApiTester.java
Reverts navikt/k9-inntektsmelding#374
=> Revert "ProsessTaskRestTjeneste fra k9-prosesstask"

pom.xml, src/main/java/no/nav/familie/inntektsmelding/server/app/forvaltning/ForvaltningApiConfig.java, src/test/java/no/nav/familie/inntektsmelding/server/RestApiTester.java
Reverts navikt/k9-inntektsmelding#376
=> Revert "K9 prosesstask tjeneste v2"

src/main/resources/db/postgres/defaultDS/V1.0_017__batch_task_rekjoring.sql
Se https://github.com/navikt/k9-inntektsmelding/pull/384
=> Lagrer batch task for rekjøring av feilede tasker

src/main/java/no/nav/familie/inntektsmelding/forvaltning/K9DokgenRestTjeneste.java
For å teste generering av pdf for inntektsmelding for omsorgspenger refusjon gjennom swagger må vi legge til de manglene feltene og mapping.
=> Legg til mapping av oms for i swagger endepunkt for generering av pdf

src/main/java/no/nav/familie/inntektsmelding/forespørsel/rest/ForespørselRest.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/rest/LukkForespørselRequestV2.java, src/main/java/no/nav/familie/inntektsmelding/typer/dto/SaksnummerDto.java
Se https://github.com/navikt/k9-inntektsmelding/pull/401
=> Bytter fagsakSaksnummer med saksnummer i resterende requester

src/main/java/no/nav/familie/inntektsmelding/forespørsel/rest/ForespørselRest.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/rest/LukkForespørselRequest.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/rest/OppdaterForespørslerRequest.java, src/main/java/no/nav/familie/inntektsmelding/forvaltning/CleanNextBucketBatchTask.java
k9-sak har gått over til v2
nå endrer vi på v1 mens den ikke er i bruk
neste steg er at k9-sak går over på v1 igjen
=> Endrer til "saksnummer" i v1-endepunkter

src/main/java/no/nav/familie/inntektsmelding/server/app/forvaltning/ForvaltningApiConfig.java
Det er ikke mulig å nå endepunktene til inntektsmelding fra swagger.
Legge de til.
=> Legger til InntektsmeldingDialogRest i swagger

.deploy/dev-gcp.json, .deploy/naiserator.yaml, .deploy/prod-gcp.json
Aktiverer audit logging av database etter krav fra Riksrevisjonen
=> aktiverer auditlogging

.deploy/dev-gcp.json, .deploy/prod-gcp.json
https://console.nav.cloud.nais.io/team/k9saksbehandling/prod-gcp/app/k9-inntektsmelding/utilization?interval=30d
=> Justerer cpu request

src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselTekster.java, src/test/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselTeksterTest.java
Kan ikke håndtere tilleggsinfo over 140 tegn
Kutter etter 137 og legger til "..."
=> Fiks: Kan ikke håndtere tilleggsinfo over 140 tegn

src/main/java/no/nav/familie/inntektsmelding/forespørsel/modell/ForespørselEntitet.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/modell/ForespørselMapper.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/modell/ForespørselRepository.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/rest/OppdaterForespørslerRequest.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjeneste.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselTjeneste.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/task/OpprettForespørselTask.java, src/main/java/no/nav/familie/inntektsmelding/imdialog/rest/InntektsmeldingDialogDto.java, src/main/java/no/nav/familie/inntektsmelding/imdialog/tjenester/InntektsmeldingTjeneste.java, src/main/java/no/nav/familie/inntektsmelding/server/jackson/JacksonJsonConfig.java, src/main/java/no/nav/familie/inntektsmelding/typer/dto/OppdaterForespørselDto.java, src/test/java/no/nav/familie/inntektsmelding/forespørsel/modell/ForespørselRepositoryTest.java, src/test/java/no/nav/familie/inntektsmelding/forespørsel/rest/ForespørselRestTest.java, src/test/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjenesteTest.java, src/test/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/task/GjenåpneForespørselTaskTest.java, src/test/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/task/OpprettForespørselTaskTest.java, src/test/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/task/SettForespørselTilUtgåttTaskTest.java, src/test/java/no/nav/familie/inntektsmelding/imdialog/modell/InntektsmeldingRepositoryTest.java, src/test/java/no/nav/familie/inntektsmelding/imdialog/tjenester/InntektsmeldingMapperTest.java, src/test/java/no/nav/familie/inntektsmelding/imdialog/tjenester/InntektsmeldingTjenesteTest.java
Av en foreløpig ukjent grunn, klarte ikke frontend å parse responsen fra /innteksmeldinger og /opplysninger. 
Legger tilbake endringene i https://github.com/navikt/k9-inntektsmelding/pull/475, men fjerner mapping av etterspurtePerioder i ForespørselEntitet til frontend dto
=> Reapply TSFF-1577: Opprett forespørsel med etterspurte perioder for omsorgspenger men uten mapping til frontend dto

src/main/java/no/nav/familie/inntektsmelding/forespørsel/modell/ForespørselEntitet.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/modell/ForespørselMapper.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/modell/ForespørselRepository.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/rest/OppdaterForespørslerRequest.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjeneste.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselTjeneste.java, src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/task/OpprettForespørselTask.java, src/main/java/no/nav/familie/inntektsmelding/imdialog/rest/InntektsmeldingDialogDto.java, src/main/java/no/nav/familie/inntektsmelding/imdialog/tjenester/InntektsmeldingTjeneste.java, src/main/java/no/nav/familie/inntektsmelding/server/jackson/JacksonJsonConfig.java, src/main/java/no/nav/familie/inntektsmelding/typer/dto/OppdaterForespørselDto.java, src/test/java/no/nav/familie/inntektsmelding/forespørsel/modell/ForespørselRepositoryTest.java, src/test/java/no/nav/familie/inntektsmelding/forespørsel/rest/ForespørselRestTest.java, src/test/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjenesteTest.java, src/test/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/task/GjenåpneForespørselTaskTest.java, src/test/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/task/OpprettForespørselTaskTest.java, src/test/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/task/SettForespørselTilUtgåttTaskTest.java, src/test/java/no/nav/familie/inntektsmelding/imdialog/modell/InntektsmeldingRepositoryTest.java, src/test/java/no/nav/familie/inntektsmelding/imdialog/tjenester/InntektsmeldingMapperTest.java, src/test/java/no/nav/familie/inntektsmelding/imdialog/tjenester/InntektsmeldingTjenesteTest.java
This reverts commit f8ecda4e2f2f51507261d50f894606a884c2fe2b.
=> Revert "Reapply TSFF-1577: Opprett forespørsel med etterspurte perioder for omsorgspenger men uten mapping til frontend dto (#477)"

src/main/java/no/nav/familie/inntektsmelding/imdialog/tjenester/InntektsmeldingMapper.java
Vi sender ikke med periodene for omsorgepenger direkte utbetaling fordi vi ikke får de slik vi gjør for omsorgspenger refusjon.
Henter ut fraværsperiodene fra etterspurte perioder på forespørselentiteten hvor de er lagret, og mapper det så til inntektsmeldingen.
Har ikke skrevet tester da det går i bena på https://github.com/navikt/k9-inntektsmelding/pull/475 
Tenker og skrive de etterpå.
=> TSFF-1715 Hent ut fraværsperioder fra forespørselEntitet i stedet for å få det fra frontend og map til inntektsmelding
