navikt/k9-inntektsmelding

- .deploy/fp/dev-gcp-teamforeldrepenger.json
- .deploy/fp/naiserator.yaml
- .deploy/fp/prod-gcp-teamforeldrepenger.json
Det blir da mulig å innhente en gyldig tokenX token for en arbeidsgiver med 
`https://tokenx-token-generator.intern.dev.nav.no/api/obo?aud=dev-gcp:teamforeldrepenger:fpinntektsmelding`
og et gyldig Azure token for kall fra fagsak med:
-  Brukerkontekst: `https://azure-token-generator.intern.dev.nav.no/api/obo?aud=dev-gcp:teamforeldrepenger:fpinntektsmelding`
- Systemkontekst: `https://azure-token-generator.intern.dev.nav.no/api/m2m?aud=dev-gcp:teamforeldrepenger:fpinntektsmelding`
Kan brukes i f.eks. postman for å simulere frontend kall til backend eller fagsystemkall til IM-backen.
https://doc.nais.io/auth/tokenx/how-to/generate/
https://doc.nais.io/auth/entra-id/how-to/generate/
> Feat: Støtte for aura token generering i dev.

- pom.xml
- src/test/java/no/nav/familie/inntektsmelding/server/exceptions/GeneralRestExceptionMapperTest.java
- src/test/resources/logback-test.xml
Fikser feilen med denne testen. Årsaken til feilen er at Logback prøver å replaye alt som ble logget i init fasen om man kjører i et multithreaded miljø - https://www.slf4j.org/codes.html#replay
Jeg har slått av multithreading ved bygging om man ikke har noe mot. Det beste er å finne ut av dette. 
Ekstra ting:
- Legger inn test konfig for secureLogger
- Legger inn Mockito som javaagent som beskrevet her: https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#0.3
- Oppdatering av biblioteker.
> Fikser GeneralExceptionMapperTest

- src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjeneste.java
- src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjenesteImpl.java
- src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselTjeneste.java
- src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/task/OpprettForespørselTask.java
- src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/task/SettForespørselTilUtgåttTask.java
- src/test/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjenesteImplTest.java
- src/test/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/task/OpprettForespørselTaskTest.java
- src/test/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/task/SettForespørselTilUtgåttTaskTest.java
Problemet vi forsøker å løse her er at vi ikke har transaksjonshåndtering mot arbeidsgiverportalen, så hvis noe feiler og db-transaksjonen rulles tilbake så blir det likevel liggende der. Dette er et problem for oppdater-tjenesten fordi den håndterer flere forespørsler i samme transaksjon. 
Å bruke prosesstasks for hver enkelt forespørsel er bare en mulig løsning. En annen mulighet er å starte egne transaksjoner per forespørsel. En fordel med prosesstasks er at vi får mulighet for retry. En (mulig) ulempe er at k9-sak/fp-sak ikke får vite at det har feilet.
> Oppdaterer forespørsler med prosesstasks for bedre feilhåndtering

- src/main/java/no/nav/familie/inntektsmelding/forespørsel/modell/ForespørselEntitet.java
- src/main/java/no/nav/familie/inntektsmelding/forespørsel/modell/ForespørselRepository.java
- src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjenesteImpl.java
- src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselTjeneste.java
- src/main/java/no/nav/familie/inntektsmelding/typer/dto/OrganisasjonsnummerDto.java
Legger til saksnummer når vi søker etter åpne forespørsler for å hindre at fp-autotest feiler på at det finnes flere enn 1 åpen forespørsel. Fikser også at vi ikke maskerer orgnummer noen steder, og at vi maskerer på lik måte på OrganisasjonsnummerDto og ForespørselEntitet.
> POFIM-96 Opprett forespørsel

- src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjenesteImpl.java
- src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/task/HåndterRekkefølgeAvForespørselTasks.java
- src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/task/OpprettForespørselTask.java
- src/test/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/task/OpprettForespørselTaskTest.java
Inspirert av https://github.com/navikt/k9-sak/blob/master/behandlingslager/domene/src/main/java/no/nav/k9/sak/behandlingslager/fagsak/H%C3%A5ndterRekkef%C3%B8lgeAvFagsakProsessTaskGrupper.java
> k9: Håndtere rekkefølge av taskgrupper med ProsessTaskLifecycleObserver

- src/main/java/no/nav/familie/inntektsmelding/forespørsel/modell/ForespørselRepository.java
- src/main/java/no/nav/familie/inntektsmelding/forespørsel/rest/ForespørselRest.java
- src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjeneste.java
- src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjenesteImpl.java
- src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselTjeneste.java
- src/test/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjenesteImplTest.java
Dersom en forespørsel har status ferdig, (inntektsmelding er mottatt), settes forespørsel likevel til ugått. Dette gjør at arbeidsgiver ikke kan sende inn endringer. Hindret i front end. Det er ikke mulig å sette ferdig oppgave til utgått i arb.giverportalen så den vil ha status utført.
> POFIM-81 Endring for endepunkt /sett-til-utgatt

- pom.xml
- src/main/java/no/nav/familie/inntektsmelding/imdialog/task/SendTilJoarkTask.java
- src/main/java/no/nav/familie/inntektsmelding/imdialog/tjenester/InntektsmeldingTjeneste.java
- src/main/java/no/nav/familie/inntektsmelding/overstyring/InntektsmeldingOverstyringTjeneste.java
Tingen er at prosesstask bruker PTData.getSaksnummer() til å sette MDC-kontekst. Vi kommer tilbake til header-saksnummer.
@oyvemb Jeg har ikke tatt tilsvarende makeover på OpprettForespørselTask. Prosesstask har standardisert setter+getter for aktørId, saksnummer, behandlingUuid . Kan være greit å gjøre endring før prodsetting.
Generelt og redaksjonelt for å være konsistent med fpsak/k9sak: 
* Jeg ser saksnummer, fagsakSaksnummer og fagsystemSaksnummer + SaksnummerDto. Selv om det er noe styr med Fager-saksnummer, så ville jeg brukt "saksnummer" for "våre" (FP + K9 har etablerte begrep) og fager eller arbeidsgiverSaksnummer for andre begrep.
* Nummer eller Nr. Er det noen grunn til å ikke spell-out nummer? Tenk lesbarhet.
* Domenetyper blir lett en runddans med varianter som tar inn …
> Bruk task-saksnummer mot joark

- src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjeneste.java
- src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjenesteImpl.java
- src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/task/OpprettForespørselTask.java
- src/test/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/task/OpprettForespørselTaskTest.java
For pleiepenger og de andre ytelsene i k9 må vi ofte etterspørre inntektsmelding for flere skjæringstidspunkter. Vi har derfor behov for å vise frem skæringstidspunktet på saken slik at arbeidsgiver kan se hva som skiller de forskjellige oppgavene. 
Jira oppgave: https://jira.adeo.no/browse/POFIM-144
Viser dato sammen med tilleggsinformasjonen slik som PO helse gjør det, men med litt egen tekst. 
Starter først med opprettet oppgave for å få feedback på hvordan det ser ut.
> Vis første fraværsdato for opprettet oppgave i sakslisten

- .deploy/fp/dev-gcp-teamforeldrepenger.json
- .deploy/fp/prod-gcp-teamforeldrepenger.json
Ref https://nav-it.slack.com/archives/CEKQHNLLU/p1735903040566749
Jeg har ikke tilgang til Entra ID Portal, men fant at man kunne verifisere ved å trikse med url på myaccount uten å være medlem av aktuell gruppe selv.
saksbehandler prod: https://myaccount.microsoft.com/groups/73107205-17ec-4a07-a56e-e0a8542f90c9
saksbehandler dev: https://myaccount.microsoft.com/groups/27e77109-fef2-48ce-a174-269074490353 (bytt til preprod-ident for å se gruppen)
> Legger til azuregruppene for saksbehandlere

- src/main/java/no/nav/familie/inntektsmelding/integrasjoner/person/PersonTjeneste.java
- src/main/java/no/nav/familie/inntektsmelding/refusjonomsorgsdagerarbeidsgiver/rest/HentInnloggetBrukerRequestDto.java
- src/main/java/no/nav/familie/inntektsmelding/refusjonomsorgsdagerarbeidsgiver/rest/InnloggetBrukerDto.java
- src/main/java/no/nav/familie/inntektsmelding/refusjonomsorgsdagerarbeidsgiver/rest/RefusjonOmsorgsdagerArbeidsgiverRest.java
- src/main/java/no/nav/familie/inntektsmelding/refusjonomsorgsdagerarbeidsgiver/rest/SlåOppArbeidstakerRequestDto.java
- src/main/java/no/nav/familie/inntektsmelding/refusjonomsorgsdagerarbeidsgiver/tjenester/InnloggetBrukerTjeneste.java
- src/main/java/no/nav/familie/inntektsmelding/server/auth/AutentiseringFilter.java
- src/test/java/no/nav/familie/inntektsmelding/integrasjoner/person/PersonTjenesteTest.java
- src/test/java/no/nav/familie/inntektsmelding/refusjonomsorgsdagerarbeidsgiver/rest/RefusjonOmsorgsdagerArbeidsgiverRestTest.java
- src/test/java/no/nav/familie/inntektsmelding/refusjonomsorgsdagerarbeidsgiver/tjenester/InnloggetBrukerTjenesteTest.java
Dette PRet legger til et endepunkt som returnerer informasjon om den innloggede brukeren.
Vi må sende med organisasjonsnummeret man er "logget inn som" som en query parameter, da dette ikke er tilgjengelig i JWTen (man er ikke faktisk logget inn som den bedriften – det man ser på Min Side Arbeidsgiver er i applikasjonslaget, ikke i autentiseringslaget). Dette kan vi løse ved at Fager legger til aktivt organisasjonsnummer som et query parameter i lenken inn i løsningen vår.
> Legg til info om innlogget bruker endepunkt

- src/main/java/no/nav/familie/inntektsmelding/integrasjoner/aareg/AaregRestKlient.java
- src/main/java/no/nav/familie/inntektsmelding/refusjonomsorgsdagerarbeidsgiver/rest/RefusjonOmsorgsdagerArbeidsgiverRest.java
- src/test/java/no/nav/familie/inntektsmelding/integrasjoner/aareg/AaregRestKlientTest.java
Om Aareg ikke finner en person, så får man en 404 feil. Siden den ikke ble catchet på noe vis av eksisterende kode, fikk man tilbake en 500 fra APIet. Det gjør at vi ikke kan differensiere mellom når en person ikke finnes, og når noe går galt rent teknisk. Det er ikke ønskelig.
Denne PRen returnerer heller en tom liste med arbeidsforhold om man får en 404 fra Aareg-integrasjonen, som gjør at vi kan vise riktig feilmelding.
> Returner tom liste dersom man får en 404 fra aareg

- .deploy/k9/prod-gcp-k9saksbehandling.json
- .github/workflows/build.yml
- .github/workflows/codeql.yml
- .github/workflows/dependency-submission.yml
**Endringer**
* Buker k9 sin workflow for å bygg, codeql og dependency-submission.
* Bruker foreløpig ft-inntektsmelding sin workflow for deploy. 
* Legger til ny jobb for deploy til prod.
**Videre**
* I neste iterasjon ønsker vi å erstatte workflow for deploy med k9 sin reuseable workflow.
> Opprett workflow for å deploye k9-inntekstmelding til prod

- src/main/java/no/nav/familie/inntektsmelding/refusjonomsorgsdager/rest/HentInntektsopplysningerResponseDto.java
- src/main/java/no/nav/familie/inntektsmelding/refusjonomsorgsdager/tjenester/RefusjonOmsorgsdagerService.java
- src/test/java/no/nav/familie/inntektsmelding/refusjonomsorgsdager/rest/RefusjonOmsorgsdagerRestTest.java
- src/test/java/no/nav/familie/inntektsmelding/refusjonomsorgsdager/tjenester/RefusjonOmsorgsdagerServiceTest.java
Under testing av innhenting av inntektsinformasjon, så la jeg merke til at inntektsmeldinger gjør litt hokus pokus med inntektsinformasjonen, som vi ikke gjør i refusjonsflyten. 
Denne PRen aligner disse to, slik at det blir likt (og at vi dermed kan bruke samme komponent på frontenden).
> Returner inntektsinfo på samme format som for vanlige inntektsmeldinger

- .deploy/naiserator.yaml
Siden vi har tatt inn k9 sin driftsrolle trenger vi ikke lenger å ha allowAllUsers. Når vi setter den til false vil kun de med denne rollen få tilgang.
Se https://doc.nais.io/auth/entra-id/how-to/secure/
> Setter allowAllUsers: false

- src/main/java/no/nav/familie/inntektsmelding/forvaltning/K9DokgenRestTjeneste.java
Oppslag for henting av person feiler når vi bruker en dummy-verdi for aktørId. 
Legger til aktørId i requesten så vi kan sende inn riktig aktørId fra swagger.
> Send inn aktørId i forvaltningsendepunkt for generering av pdf

- src/main/java/no/nav/familie/inntektsmelding/forvaltning/RekjørFeiledeTasksBatchTask.java
Vi bør ta stilling til om dette er noe vi ønsker, eller om vi heller vil ta tak i hver enkelt feilende task manuelt.
Fordelen med å ha en batch task er at midlertidige feil, fks av typen "Får ikke kontakt med eksternt system", kan løse seg av seg selv ved rekjøring.
> Batch task for å rekjøre feilende tasker

- src/main/java/no/nav/familie/inntektsmelding/imdialog/rest/ArbeidsgiverinitiertDialogRest.java
- src/main/java/no/nav/familie/inntektsmelding/refusjonomsorgsdager/rest/SlåOppArbeidstakerResponseDto.java
- src/main/java/no/nav/familie/inntektsmelding/refusjonomsorgsdager/tjenester/RefusjonOmsorgsdagerService.java
- src/test/java/no/nav/familie/inntektsmelding/refusjonomsorgsdager/rest/RefusjonOmsorgsdagerRestTest.java
- src/test/java/no/nav/familie/inntektsmelding/refusjonomsorgsdager/tjenester/RefusjonOmsorgsdagerServiceTest.java
Vi ønsker å vise organisasjonsnavnet for arbeidsgiveren for en enklere visuell bekreftelse i skjemaet for omsorgspenger refusjon.
Henter organisasjonsnavnet tilsvarende som vi gjør i `InntektsmeldingTjeneste`.
> Hent organisasjonsnavn for arbeidsforholdene ved henting av arbeidstaker

- .deploy/prod-gcp.json
Vi bruker mye mindre enn vi spør om, se https://console.nav.cloud.nais.io/team/k9saksbehandling/prod-gcp/app/k9-inntektsmelding/utilization?interval=30d
200m er det samme som k9-sak spør om. k9-inntektsmelding bør hvertfall ikke trenge mer enn k9-sak.
> Justerer CPU request i prod

- src/main/java/no/nav/familie/inntektsmelding/integrasjoner/arbeidsgivernotifikasjon/Merkelapp.java
- src/test/java/no/nav/familie/inntektsmelding/integrasjoner/arbeidsgivernotifikasjon/MerkelappTest.java
Vi ønsker egentlig å markere saker for omsorgspenger med "Refusjonskrav omsorgspenger". Det viser seg at vi er nødt til å legge dette inn i team Fager sin liste over godkjente merkelapper. 
Nå feiler innsending pga merkelappen og hindrer videre testing. 
Bruker den godkjente merkelappen inntil den nye er lagt inn i Fager.
> Fiks merkelapp for omsorgspenger så det matcher den Fager har

- src/main/java/no/nav/familie/inntektsmelding/integrasjoner/dokgen/InntektsmeldingPdfData.java
- src/main/java/no/nav/familie/inntektsmelding/integrasjoner/dokgen/InntektsmeldingPdfDataMapper.java
- src/main/java/no/nav/familie/inntektsmelding/integrasjoner/dokgen/K9DokgenKlient.java
- src/main/java/no/nav/familie/inntektsmelding/integrasjoner/dokgen/K9DokgenTjeneste.java
- src/main/java/no/nav/familie/inntektsmelding/integrasjoner/dokgen/OmsorgspengerRefusjonPdfData.java
- src/main/java/no/nav/familie/inntektsmelding/integrasjoner/dokgen/OmsorgspengerRefusjonPdfDataMapper.java
- src/test/java/no/nav/familie/inntektsmelding/integrasjoner/dokgen/K9DokgenKlientTest.java
Vi har opprettet et nytt endepunkt for å generere pdf for omsorgspenger refusjon for å speile oppsummeringen til den flyten. Endringene i pdfen ble innlemmet her: https://github.com/navikt/k9-dokgen/pull/275
Tilhørende Jira: https://jira.adeo.no/browse/POFIM-204
- Oppretter eget pdf objekt for omsorgspenger refusjon og tar i bruk det nye endepunktet
- Fjerner omsorgspenger-data fra "vanlig" inntektsmelding-pdf
Fjerner omsorgspenger fra "vanlig" inntektsmelding-pdf her: https://github.com/navikt/k9-dokgen/pull/276
> POFIM-204: Generer pdf for omsorgspenger refusjon med nytt endepunkt

- src/main/java/no/nav/familie/inntektsmelding/imdialog/modell/InntektsmeldingRepository.java
- src/main/java/no/nav/familie/inntektsmelding/imdialog/rest/InntektsmeldingDialogRest.java
- src/main/java/no/nav/familie/inntektsmelding/imdialog/tjenester/InntektsmeldingTjeneste.java
- src/test/java/no/nav/familie/inntektsmelding/imdialog/modell/InntektsmeldingRepositoryTest.java
Når arbeidsgiver skal fylle ut sitt refusjonskrav for en gitt aktør vet ikke vedkommende hva hen har sendt inn tidligere. Vi ønsker derfor en oversikt over alle tidligere innsendte inntektsmeldinger.
Jira: https://jira.adeo.no/browse/POFIM-213
Lager et endepunkt som henter ut alle inntektsmeldinger for en arbeidsgiver og dens ansatte og det aktuelle året.
Lager også en ny repository-metode som henter ut inntektsmeldingene gitt året som er angitt i startDato for kravet.
> Endepunkt som henter alle im for ett gitt år

- .github/pull_request_template.md
For å senke terskelen for å dokumentere hvorfor man gjør endringer, hva endringen går ut på og måten man har løst det på, har vi bestemt oss for å legge til en template for pull requester med overskrifter som gir konteksten som vi ønsker.
> Legg til pull request template

- src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjeneste.java
- src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselTekster.java
- src/main/java/no/nav/familie/inntektsmelding/imdialog/tjenester/InntektsmeldingTjeneste.java
- src/test/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjenesteTest.java
- src/test/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselTeksterTest.java
Hver inntektsmelding på "min side arbeidsgiver" viser startdato for kravet. Dette gir lite informasjon for refusjonskrav omsorgspenger da det som regel søkes for flere perioder og enkeltdager. Vil vil derfor endre tilleggsinfo til å vise periodene og enkeltdagene oppramset, som for eksempel slik: "For 01.04.25, 02.04.25." etc.
Jira: https://jira.adeo.no/browse/POFIM-216
Sender derfor med fraværsperiodene og fraværsdagene i stedet for startdato/skjæringstidspunkt til generering av teksten som kalles tilleggsinfo.
Kutter deretter opp periodene i enkeltdager og legger de i én liste sammen med enkeltdagene (delvis fravær) og sorterer de kronologisk.
> POFIM-216 Legger til perioder i tilleggsinfo for refusjonskrav omsorgspenger

- src/main/java/no/nav/familie/inntektsmelding/forespørsel/modell/ForespørselRepository.java
- src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjeneste.java
- src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselTjeneste.java
- src/main/java/no/nav/familie/inntektsmelding/imdialog/tjenester/InntektsmeldingTjeneste.java
- src/test/java/no/nav/familie/inntektsmelding/imdialog/tjenester/InntektsmeldingTjenesteTest.java
Metoden `finnForespørsler` hentet egentlig kun de som er under behandling. Vi ønsker alle uansett status.
Renamet `finnForespørsler` til `finnForespørslerUnderBehandling` og laget en ny metode som heter `finnAlleForespørsler`.
> POFIM-213 Finner alle forespørsler i stedet for kun under behandling

- src/main/java/no/nav/familie/inntektsmelding/forvaltning/ForespørselForvaltningRestTjeneste.java
- src/main/java/no/nav/familie/inntektsmelding/imdialog/modell/InntektsmeldingRepository.java
- src/main/java/no/nav/familie/inntektsmelding/server/app/forvaltning/ForvaltningApiConfig.java
I utgangspunktet burde alle inntektsmeldinger være tilknyttet en forespørsel. Vi ønsker derfor å kjøre et migreringsscript som setter kolonnen `forespoersel_id` i InntektsmeldingEntitet til `not null`, men vi må undersøke om det faktisk stemmer så ikke flyway kræsjer. 
Relevant PR: https://github.com/navikt/k9-inntektsmelding/pull/425
Jira: https://jira.adeo.no/browse/POFIM-212
Legger til et swagger endepunkt som teller antall inntektsmeldinger som har `forespoersel_id = null`. Ved å gjøre det gjennom swagger får vi med begrunnelse for hvorfor man har kikket på data i prod, som er fint selv om det ikke er noe sensitiv data i denne spørringen. 
Fjerner InntektsmeldingDialogRest fra swagger som ikke brukes.
> POFIM-212: Legg til endepunkt i swagger for å telle antall inntektsmeldinger som ikke har en forespørsel

- src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselTekster.java
- src/test/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselTeksterTest.java
Ref Jira: https://jira.adeo.no/browse/POFIM-216
Ble uoversiktlig med enkeldager da de i teorien kan være mange.
Viser tilleggsinfo heller som antall dager per måned, som "For 7 dager i mars, 1 dag i april."
> POFIM-216 Endrer tekst fra enkeltdatoer til antall i hver måned

- src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjeneste.java
For å slippe å laste frontend to ganger ønsker vi å lenke direkte til rikting frontend-side.
Oppdaterer lenken for redirect for refusjon omsorgspenger
> Fiks: Endre lenken for refusjon omsorgspenger

- src/main/java/no/nav/familie/inntektsmelding/integrasjoner/dokgen/InntektsmeldingPdfDataMapper.java
- src/main/java/no/nav/familie/inntektsmelding/integrasjoner/dokgen/K9DokgenTjeneste.java
- src/main/java/no/nav/familie/inntektsmelding/integrasjoner/dokgen/Omsorgspenger.java
- src/main/java/no/nav/familie/inntektsmelding/integrasjoner/dokgen/OmsorgspengerRefusjonPdfDataMapper.java
I oppsummeringen viser vi trukket periode under en egen overskrift og ikke bare som en delvis periode med 0 timer. 
Jira: https://jira.adeo.no/browse/TSFF-1423
Trekk ut trukket periode som eget datafelt til pdf-en
Relatert PR: https://github.com/navikt/k9-dokgen/pull/286
- Fjerner ubrukt metode `mapOmsorgspenger()`
- Rename genererPdf -> genererPdfForInntektsmelding
> TSFF-1423: Vis trukket periode på pdfen

- src/main/java/no/nav/familie/inntektsmelding/metrikker/StatistikkMetrikkTask.java
- src/main/java/no/nav/familie/inntektsmelding/prosesstask/ProsessTaskRepository.java
Vi har behov for en oversikt over taskfeil for å sørge for trygg drift av k9-inntektsmelding.
Jira: https://jira.adeo.no/browse/TSFF-1364
Oppretter en statistikk-task som slår opp feilende tasker i databasen og oppdaterer en gauge metrikk i prometheus.
> TSFF-1364: Legg til ny StatistikkMetrikkTask for monitorering av taskfeil

- .deploy/naiserator.yaml
Vi ønsker å slå på tracing og logging til både Loki (Grafana) og Elastic.
Slår på tracing og logging
> TSFF-1378: Slå på tracing og logging til grafana

- .deploy/naiserator.yaml
I forbindelse med https://github.com/navikt/k9-inntektsmelding/pull/447 la vi inn tracing til elastic. Det er ikke tilgjengelig i gcp. 
Fjerner "elastic-apm"
> TSFF-1378: Slå på tracing og logging til grafana 2

- src/main/java/no/nav/familie/inntektsmelding/server/exceptions/JsonMappingExceptionMapper.java
Vi oppdaget at vi får en json mapping feil i loggene. Det er lite info så vi må legge på mer info.
Legger til stack trace i log meldingen
> Fiks: Legg til stack trace for json mapping error

- src/main/java/no/nav/familie/inntektsmelding/server/exceptions/JsonMappingExceptionMapper.java
Reverts navikt/k9-inntektsmelding#450
Vi ønsket å legge til mer logging for å finne ut av hva som gikk galt. Nå viser det seg at vi har funnet feilen og har ikke samme behov lenger. Siden stack trace av en json parsing feil _kan_ inneholde sensitiv info, ønsker vi å reverte denne.
> Revert "Fiks: Legg til stack trace for json mapping error"

- src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjeneste.java
- src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselTekster.java
- src/main/java/no/nav/familie/inntektsmelding/imdialog/tjenester/InntektsmeldingTjeneste.java
- src/main/java/no/nav/familie/inntektsmelding/integrasjoner/arbeidsgivernotifikasjon/Merkelapp.java
- src/main/java/no/nav/familie/inntektsmelding/integrasjoner/dokgen/K9DokgenTjeneste.java
- src/main/java/no/nav/familie/inntektsmelding/integrasjoner/joark/JoarkTjeneste.java
- src/main/java/no/nav/familie/inntektsmelding/integrasjoner/person/PersonTjeneste.java
- src/main/java/no/nav/familie/inntektsmelding/refusjonomsorgsdager/tjenester/RefusjonOmsorgsdagerService.java
- src/test/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjenesteTest.java
- src/test/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselTeksterTest.java
- src/test/java/no/nav/familie/inntektsmelding/imdialog/tjenester/InntektsmeldingTjenesteTest.java
- src/test/java/no/nav/familie/inntektsmelding/integrasjoner/arbeidsgivernotifikasjon/MerkelappTest.java
- src/test/java/no/nav/familie/inntektsmelding/integrasjoner/joark/JoarkTjenesteTest.java
- src/test/java/no/nav/familie/inntektsmelding/refusjonomsorgsdager/tjenester/RefusjonOmsorgsdagerServiceTest.java
Når vi oppretter forespørsel for vanlig inntektsmelding for omsorgspenger, ønsker vi å bruke en egen merkelapp og sakstittel.
Jira: https://jira.adeo.no/browse/TSFF-1733
- Legger til egen ny merkelapp `INNTEKTSMELDING_OMS("Inntektsmelding omsorgspenger")` (skal være støttet av Fager)
- Legger til egen metode for å hente sakstittel for refusjonskrav og for inntektsmelding. 
- Fjern ubrukt parameter ytelseType i hentPersonInfoFraAktørId og hentPersonFraIdent i PersonTjeneste
> TSFF-1733: Legg til riktig merkelapp og sakstittel ved opprettelse av forespørsel for vanlig inntektsmelding for omsorgspenger

- src/main/java/no/nav/familie/inntektsmelding/forespørsel/modell/ForespørselEntitet.java
- src/main/java/no/nav/familie/inntektsmelding/forespørsel/modell/ForespørselRepository.java
- src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjeneste.java
- src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselTjeneste.java
- src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/task/OppdaterForespørselTask.java
- src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/task/OpprettForespørselTask.java
- src/main/java/no/nav/familie/inntektsmelding/typer/dto/ForespørselOppdatering.java
- src/test/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjenesteOppdaterTest.java
- src/test/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjenesteTest.java
- src/test/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/task/OppdaterForespørselTaskTest.java
For å vise frem riktige perioder til arbeidsgiver når de fyller ut inntektsmeldingen må vi oppdatere forespørslene med riktig etterspurte perioder. 
Jira: https://jira.adeo.no/browse/TSFF-1742
Oppretter `OppdaterForespørselTask` som kun skal oppdatere etterspurte perioder dersom følgene krav er oppfylt:
1. `ytelseType = OMSORGSPENGER`
2. ForespørselDto-en har status `OPPRETT`
3. Den eksisterende forespørsel entiteten har status `UNDER_BEHANDLING`
4. De har forskjellige etterspurte perioder. Hvis de er forskjellige skal vi overskrive med de nye periodene vi får fra k9-sak
- Endrer fra entityManager.persist til entityManager.merge der vi skal gjøre oppdateringer i databasen
> TSFF-1742: oppdater etterspurte perioder på forespørsel 

- src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/ForespørselBehandlingTjeneste.java
- src/main/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/task/OppdaterForespørselTask.java
- src/test/java/no/nav/familie/inntektsmelding/forespørsel/tjenester/task/OppdaterForespørselTaskTest.java
Dersom bruker søker om nye perioder innenfor 4 uker fra skjæringstidspunkt, skal vi oppdatere forespørselen med de nye periodene. Da må også tilleggsinformasjonen oppdateres. 
Jira: https://jira.adeo.no/browse/TSFF-1852
Oppdaterer tilleggsinformasjonen ved oppdatering av forespørsel.
> TSFF-1852: Oppdater tilleggsinformasjonen med nye antall fraværsdager

- src/main/java/no/nav/familie/inntektsmelding/imdialog/rest/ArbeidsgiverinitiertDialogRest.java
- src/main/java/no/nav/familie/inntektsmelding/imdialog/rest/HentOpplysningerResponse.java
- src/main/java/no/nav/familie/inntektsmelding/imdialog/rest/InntektsmeldingDialogDto.java
- src/main/java/no/nav/familie/inntektsmelding/imdialog/rest/InntektsmeldingDialogRest.java
- src/main/java/no/nav/familie/inntektsmelding/imdialog/tjenester/InntektsmeldingMottakTjeneste.java
- src/main/java/no/nav/familie/inntektsmelding/imdialog/tjenester/InntektsmeldingTjeneste.java
- src/main/java/no/nav/familie/inntektsmelding/typer/dto/InnsenderDto.java
- src/main/java/no/nav/familie/inntektsmelding/typer/dto/InntektsopplysningerDto.java
- src/main/java/no/nav/familie/inntektsmelding/typer/dto/MånedsinntektDto.java
- src/main/java/no/nav/familie/inntektsmelding/typer/dto/OrganisasjonInfoDto.java
- src/main/java/no/nav/familie/inntektsmelding/typer/dto/PersonInfoDto.java
- src/test/java/no/nav/familie/inntektsmelding/imdialog/tjenester/InntektsmeldingMottakTjenesteTest.java
- src/test/java/no/nav/familie/inntektsmelding/imdialog/tjenester/InntektsmeldingTjenesteTest.java
Vi har behov for å refaktorere koden i InntektsmeldingTjenesten før vi begynner å utvide med ny funksjonalitet for å støtte arbeidsgiver initiert inntektsmelding.
- Trekker ut metoder for mottak av inntektsmelding fra InntektsmeldingTjeneste til ny InntektsmeldingMottatTjeneste
- Trekker ut dto-er i InntektsmeldingDialogDto til egne filer
- Renamer InntektsmeldingDialogDto –> HentOpplysningerResponse så det stemmer med metoden hentOpplysninger() i InntektsmeldingDialogRest
> Chore: rydder i inntektsmelding tjeneste

- src/main/java/no/nav/familie/inntektsmelding/imdialog/rest/ArbeidsgiverinitiertDialogRest.java
- src/main/java/no/nav/familie/inntektsmelding/imdialog/tjenester/GrunnlagTjeneste.java
- src/test/java/no/nav/familie/inntektsmelding/imdialog/tjenester/GrunnlagTjenesteTest.java
Dersom en bruker bytter jobb samtidig som de mottar en ytelse, vil ikke k9-sak utlede at det mangler en inntektsmelding. Det vil derfor ikke bli opprettet en forespørsel for den nye arbeidsgiveren dersom de ønsker å refundere. 
For å støtte at arbeidsgivere sende inne en inntektsmelding hvor de ber om refusjon for nyansatte, må vi hente opplysninger på en litt annen måte.
Jira: https://jira.adeo.no/browse/TSFF-1932
- Mye av funksjonaliteten er allerede på plass fra da vi delte kodebase med foreldrepenger. 
- Legger til forklarende kommentarer
> TSFF-1932: Hent opplysninger for arbeidsgiverinitiert inntektsmelding for nyansatt

- pom.xml
- src/main/java/no/nav/familie/inntektsmelding/imdialog/rest/ArbeidsgiverinitiertDialogRest.java
- src/main/java/no/nav/familie/inntektsmelding/integrasjoner/k9sak/FagsakInfo.java
- src/main/java/no/nav/familie/inntektsmelding/integrasjoner/k9sak/K9SakKlient.java
- src/main/java/no/nav/familie/inntektsmelding/integrasjoner/k9sak/K9SakTjeneste.java
- src/main/java/no/nav/familie/inntektsmelding/typer/dto/PeriodeDto.java
- src/main/resources/application-dev-gcp.properties
- src/main/resources/application-prod-gcp.properties
Dersom man forsøker å sende inne en inntektsmelding på en person og vi ikke finner en sak på i k9, skal ikke arbeidsgiver få lov til å sende inn. Feilmelding til arbeidsgiver i disse tilfellene: "Du kan ikke sende inn inntektsmelding på {ytelsetype} på denne personen".
Jira: https://jira.adeo.no/browse/TSFF-1746
- Ny integrasjon til k9-sak: K9SakKlient
- Henter saker i k9 i endepunktet som henter arbeidsforhold: `/arbeidsforhold`.
Importerer kontraktene til k9-sak. På sikt burde vi legge request- og respons-objektene som endepunktene for opprettelse, henting, osv... av forespørsler bruker i dag.
> TSFF-1746: Sjekk om det finnes sak i k9

- pom.xml
- src/main/java/no/nav/familie/inntektsmelding/imdialog/rest/ArbeidsgiverinitiertDialogRest.java
- src/main/java/no/nav/familie/inntektsmelding/integrasjoner/k9sak/FagsakInfo.java
- src/main/java/no/nav/familie/inntektsmelding/integrasjoner/k9sak/K9SakKlient.java
- src/main/java/no/nav/familie/inntektsmelding/integrasjoner/k9sak/K9SakTjeneste.java
Vi ønsker ikke å sende inn inntektsmeldinger som ikke treffer en søknadsperiode. Tidligere sjekket vi mot `gyldigPeriode`, men det kan være opphold innenfor den gyldige perioden som vi ikke ønsker å få med. 
K9-sak har nå utvidet responsen slik at vi kan sjekke mot søknadsperiode. https://github.com/navikt/k9-sak/pull/12124
Jira: https://github.com/navikt/k9-sak/pull/12124
- Bumper k9-kontrakt for å få med søknadsperiodene. 
- sjekker om stp fra inntektsmeldingen treffer en av søknadsperiodene
> TSFF-1746: Hent søknadsperiodene fra brukers saker i k9 og sjekk om stp treffer en søknadsperidoe

- src/main/java/no/nav/familie/inntektsmelding/forvaltning/OppgaverForvaltningRestTjeneste.java
- src/main/java/no/nav/familie/inntektsmelding/imdialog/modell/InntektsmeldingRepository.java
Vi ønsker å utvide InntektsmeldingEntitet med nytt felt: InntektsmeldingType. Vi må derfor lage et migreringsscript og trenger oversikt over hvor mange rader som blir berørt for å ikke ta ned applikasjonen under migreringen.
Jira: https://jira.adeo.no/browse/TSFF-2020
Lager nytt forvaltningsendepunkt som henter antall rader i INNTEKTSMELDING tabellen.
> TSFF-2020: Nytt forvaltningsendepunkt for å hente anatall rader i inntektsmeldingtabellen

- src/main/java/no/nav/familie/inntektsmelding/forvaltning/K9DokgenRestTjeneste.java
- src/main/java/no/nav/familie/inntektsmelding/imdialog/task/SendTilJoarkTask.java
- src/main/java/no/nav/familie/inntektsmelding/integrasjoner/joark/JoarkTjeneste.java
- src/test/java/no/nav/familie/inntektsmelding/imdialog/task/InntektsmeldingXMLMapperTest.java
- src/test/java/no/nav/familie/inntektsmelding/imdialog/task/InntektsmeldingXMLTjenesteTest.java
- src/test/java/no/nav/familie/inntektsmelding/imdialog/tjenester/InntektsmeldingMapperTest.java
- src/test/java/no/nav/familie/inntektsmelding/integrasjoner/dokgen/InntektsmeldingPdfDataMapperTest.java
- src/test/java/no/nav/familie/inntektsmelding/integrasjoner/dokgen/OmsorgspengerInntektsmeldingPdfDataMapperTest.java
- src/test/java/no/nav/familie/inntektsmelding/integrasjoner/dokgen/OmsorgspengerRefusjonPdfDataMapperTest.java
- src/test/java/no/nav/familie/inntektsmelding/integrasjoner/joark/JoarkTjenesteTest.java
Vi har behov for å sende med InntektsmeldingType i inntektsmeldingen slik at k9-sak kan godta inntektsmeldinger som ikke ligger på skjæringstidspunkt dersom de er av typen ARBEIDSGIVERINITIERT.
Jira: https://jira.adeo.no/browse/TSFF-2113
XML-kontrakten til inntektsmeldingen er det ikke vi som eier, så vi kan ikke gjøre endringer på den. Sender derfor InntektsmeldingType som en del av tilleggsopplysninger i journalposten.
- https://github.com/navikt/k9-abakus/pull/352
- https://github.com/navikt/k9-sak/pull/12191
> TSFF-2113: Send InntektsmeldingType som tilleggsopplysninger i journalposten
